-- ---------- NUEVAS PREGUNTAS IMPORTADAS (26-06-2026) ----------
insert into public.questions
  (topic_id, text, option_a, option_b, option_c, option_d, correct_option, difficulty, explanation) values
  ('66666666-6666-6666-6666-666666666661',
   '¿Qué unidad del hospital es responsable de la apertura, conservación, custodia y distribución de las Historias Clínicas?',
   'La Unidad de Gestión Clínica',
   'La Unidad de Archivo de Historias Clínicas',
   'El Servicio de Urgencia',
   'La Subdirección Médica',
   'b', 'basic',
   'Según los protocolos del HPM, la Unidad de Archivo de Historias Clínicas es la responsable institucional de la apertura, conservación, custodia y distribución de las fichas clínicas.'),

  ('66666666-6666-6666-6666-666666666661',
   '¿Está permitido que la Historia Clínica salga físicamente del establecimiento hospitalario?',
   'Sí, si lo autoriza el médico tratante',
   'Sí, si el paciente lo solicita en OIRS',
   'No, bajo ningún punto de vista debe salir del establecimiento',
   'Sí, si el paciente firma un formulario de responsabilidad',
   'c', 'basic',
   'La normativa institucional es clara y taxativa: bajo ningún punto de vista la Historia Clínica debe salir del establecimiento. Las copias se solicitan a través de OIRS.'),

  ('66666666-6666-6666-6666-666666666662',
   '¿Qué información debe contener visiblemente la credencial de un funcionario del HPM?',
   'Solo el nombre completo y la fotografía',
   'Nombre, RUT, cargo y unidad de gestión clínica a la que pertenece',
   'Solo el nombre y el cargo del funcionario',
   'El RUT, la especialidad médica y el número de matrícula profesional',
   'b', 'basic',
   'La credencial del HPM incluye: nombre completo, RUT, cargo (ej: Ingeniero Comercial Quirúrgico) y la Unidad de Gestión Clínica a la que pertenece el funcionario.'),

  ('44444444-4444-4444-4444-444444444444',
   '¿Cuál es el segundo paso del protocolo de Clave Roja después de prestar asistencia al afectado?',
   'Trasladar al paciente a la Urgencia de inmediato',
   'Pedir a otro funcionario que llame al #121 para activar la Clave Roja',
   'Llamar al médico jefe del servicio',
   'Buscar el desfibrilador del servicio',
   'b', 'basic',
   'El paso 2 del protocolo es pedir a otro funcionario que active la Clave Roja llamando al #121, especificando si el afectado es Adulto, Niño o Embarazada.'),

  ('33333333-3333-3333-3333-333333333333',
   '¿Cómo se debe tratar una inyección accidental con medicamentos antineoplásicos?',
   'Aplicar torniquete en la zona proximal',
   'Tratarla como extravasación',
   'Lavar con agua oxigenada y cubrir con gasa',
   'Aspirar el medicamento con jeringa y luego lavar',
   'b', 'basic',
   'El protocolo del HPM establece que una inyección accidental con antineoplásicos debe tratarse como extravasación, siguiendo el protocolo específico para esa situación.'),

  ('55555555-5555-5555-5555-555555555555',
   '¿Cuál es el objetivo principal del Comité de Ética Asistencial (CEA) del HPM?',
   'Sancionar a los funcionarios que cometan errores clínicos',
   'Analizar y asesorar sobre dilemas éticos relacionados con la atención clínica de los pacientes',
   'Aprobar los protocolos de investigación científica del hospital',
   'Supervisar el cumplimiento de los derechos laborales del personal de salud',
   'b', 'basic',
   'El objetivo del CEA es analizar y asesorar sobre dilemas éticos relacionados con la atención clínica de los pacientes, no sancionar ni aprobar investigaciones.'),

  ('66666666-6666-6666-6666-666666666664',
   '¿En qué lugares físicos dentro del hospital puede un usuario ingresar un reclamo o sugerencia a través de buzón?',
   'En el hall de Urgencia y en la sala de espera de Policlínico',
   'En el Servicio de Urgencia y en el hall del Hospital Amigo',
   'Solo en la Oficina OIRS del acceso principal',
   'En la Dirección del Hospital y en la UTI Médica',
   'b', 'basic',
   'Existen dos buzones físicos: uno en el Servicio de Urgencia (buzón A) y otro en el hall del Hospital Amigo (buzón B). Además está la Oficina OIRS en el acceso principal y la página web oirs.minsal.cl.'),

  ('66666666-6666-6666-6666-666666666665',
   '¿Qué significa el término ''Zona de Derivación'' en el contexto del protocolo de Evacuación Organizada (Código Verde)?',
   'El lugar donde se concentran los funcionarios para recibir instrucciones',
   'El área predefinida de cada servicio como punto de reunión inicial',
   'El lugar al que se deben dirigir los pacientes para ser trasladados en ambulancia a otros centros',
   'La vía de escape principal del edificio',
   'c', 'basic',
   'La Zona de Derivación es el lugar al que se deben dirigir los pacientes para su posterior traslado en ambulancia a otros centros asistenciales, distinto del Punto de Reunión de funcionarios.'),

  ('66666666-6666-6666-6666-666666666661',
   'Un Servicio Clínico va a dar el alta a un paciente. ¿Qué obligación tiene respecto de la Historia Clínica al entregarla?',
   'Entregarla en el orden en que se fueron agregando los documentos, sin importar la fecha',
   'Entregarla ordenada cronológicamente y con todos los documentos relativos al episodio',
   'Entregarla solo con las evoluciones médicas y la epicrisis',
   'Entregarla directamente al paciente para que la lleve a su próxima consulta',
   'b', 'intermediate',
   'Cada Servicio Clínico tiene la obligatoriedad de entregar la Historia Clínica ordenada cronológicamente y con TODOS los documentos relativos al episodio: ingreso, evoluciones, consentimientos, protocolos operatorios, biopsias y epicrisis.'),

  ('66666666-6666-6666-6666-666666666661',
   '¿Cuál es el propósito del Sistema Informático de Trazabilidad en relación con la Historia Clínica?',
   'Registrar los diagnósticos del paciente para estadísticas ministeriales',
   'Registrar los movimientos de la Historia Clínica para ubicarla oportunamente para la atención',
   'Controlar el acceso del personal no autorizado a los datos del paciente',
   'Generar automáticamente la epicrisis al momento del alta',
   'b', 'intermediate',
   'El Sistema Informático de Trazabilidad permite registrar los movimientos de la Historia Clínica dentro del establecimiento para poder ubicarla oportunamente cuando se necesite para la atención del paciente.'),

  ('66666666-6666-6666-6666-666666666664',
   'Además del buzón físico y la oficina OIRS, ¿por qué otro canal puede un usuario ingresar un reclamo o felicitación?',
   'Por llamado telefónico al número de centralita del hospital',
   'Por la página web oirs.minsal.cl',
   'Por correo electrónico directo a la Dirección del Hospital',
   'A través de la aplicación móvil del Ministerio de Salud',
   'b', 'intermediate',
   'Los tres canales disponibles son: los buzones físicos (Urgencia y Hospital Amigo), la Oficina OIRS en el acceso principal y la página web oirs.minsal.cl.'),

  ('33333333-3333-3333-3333-333333333333',
   '¿Cuál es la diferencia en el primer auxilio entre un ''Contacto Piel'' y un ''Corte con Material Contaminado'' con antineoplásicos?',
   'No hay diferencia; ambos se tratan exactamente igual',
   'El contacto piel requiere aplicar crema antibiótica; el corte requiere solo lavado',
   'Ambos se lavan 10-15 minutos, pero el corte con material contaminado además debe dejarse secar al aire libre',
   'El contacto piel se lava con agua caliente; el corte se lava con suero frío',
   'c', 'intermediate',
   'Ambos tipos de accidente se lavan con agua o suero fisiológico por 10 a 15 minutos. La diferencia es que el corte con material contaminado tiene el paso adicional de dejar secar la zona al aire libre.'),

  ('33333333-3333-3333-3333-333333333333',
   'Tras sufrir un accidente con antineoplásicos, ¿cuál es el segundo paso del protocolo después de realizar los primeros auxilios?',
   'Notificar oficialmente como accidente de trabajo generando la DIAT',
   'Acudir inmediatamente a Urgencia sin avisar a nadie',
   'Informar inmediatamente al jefe directo o quien lo reemplace',
   'Completar un formulario de registro interno del servicio',
   'c', 'intermediate',
   'El protocolo de accidentes con antineoplásicos establece 3 pasos: 1) Primeros auxilios según el tipo de accidente, 2) Informar inmediatamente al jefe directo o quien lo reemplace, 3) Notificar oficialmente como accidente de trabajo.'),

  ('55555555-5555-5555-5555-555555555555',
   '¿A qué correo y con qué información se accede al Comité de Ética Científico (CEC) para presentar un proyecto de investigación?',
   'A eticaclinica@ssdr.gob.cl con el resumen de la Historia Clínica',
   'A comiteeticocientifico@ssdr.gob.cl, dirigiendo el proyecto al presidente del CEC',
   'A investigacion@hospitalpuertomontt.cl con el protocolo de investigación',
   'Al mismo correo del CEA, quienes derivan al CEC si corresponde',
   'b', 'intermediate',
   'Los proyectos de investigación deben dirigirse al presidente del CEC al correo comiteeticocientifico@ssdr.gob.cl. El correo eticaclinica@ssdr.gob.cl corresponde al CEA, que tiene una función distinta.'),

  ('44444444-4444-4444-4444-444444444444',
   'En el protocolo de activación de Clave Roja, ¿quién debe realizar físicamente la llamada al #121?',
   'El propio funcionario que detecta la emergencia, interrumpiendo la asistencia',
   'Otro funcionario diferente al que está prestando asistencia al afectado',
   'Exclusivamente el jefe del servicio o quien esté a cargo',
   'El personal de seguridad o portería del hospital',
   'b', 'intermediate',
   'El protocolo indica que el funcionario que detecta la emergencia debe prestar asistencia y pedir a OTRO funcionario que realice la llamada al #121, para no interrumpir la atención del afectado.'),

  ('66666666-6666-6666-6666-666666666663',
   'En el protocolo de Exposición a Fluidos Corporales, ¿cuál es la importancia de identificar al paciente fuente?',
   'Para determinar quién paga los costos del tratamiento del funcionario',
   'Para definir el tratamiento médico a seguir para el funcionario accidentado',
   'Para notificar a sus familiares del incidente ocurrido',
   'Para evaluar si el paciente fuente debe ser trasladado a aislamiento',
   'b', 'intermediate',
   'Identificar al paciente fuente es el paso 3 del protocolo de exposición a fluidos, y su objetivo es definir el tratamiento médico a seguir para el funcionario accidentado, ya que la profilaxis depende del estado serológico del paciente fuente.'),

  ('66666666-6666-6666-6666-666666666661',
   'CASO CLÍNICO: Una enfermera del Servicio de Medicina ingresa al sistema digital con su clave personal y, sin usar el RUT del paciente, navega por varios registros clínicos para buscar a un familiar suyo hospitalizado. ¿Cuál es la falla más grave que está cometiendo?',
   'Está consultando la Historia Clínica fuera del horario habitual de trabajo',
   'Está accediendo a información confidencial y datos sensibles sin el RUT del paciente, vulnerando la confidencialidad de la Historia Clínica',
   'Está usando el sistema digital en vez del formato papel, lo que no está permitido para personal de enfermería',
   'No está cometiendo ninguna falta, ya que tiene clave de acceso al sistema',
   'b', 'advanced',
   'El acceso digital a la Historia Clínica requiere dos elementos: la clave personal del funcionario Y el RUT específico del paciente. La Historia Clínica es dato sensible y confidencial. Acceder libremente sin el RUT del paciente vulnera la confidencialidad, independientemente de tener clave de sistema.'),

  ('44444444-4444-4444-4444-444444444444',
   'CASO CLÍNICO: En la sala de espera de Policlínico, una auxiliar de servicio encuentra a un hombre adulto caído en el suelo, inconsciente y con respiración agónica. En ese momento está sola en el pasillo. ¿Cuál es la secuencia de acciones correctas?',
   'Ir a buscar primero al médico de guardia, luego volver y prestar asistencia',
   'Llamar al #121 desde el citófono más cercano y luego acercarse al paciente',
   'Prestar asistencia inmediata al afectado y pedir a la primera persona que aparezca que llame al #121',
   'Esperar a que llegue otro funcionario para activar el protocolo de forma conjunta',
   'c', 'advanced',
   'El paso 1 siempre es prestar asistencia al afectado. El paso 2 es pedir a OTRO funcionario que llame al #121. Si está sola, debe comenzar la asistencia inmediatamente y solicitar ayuda al primer transeúnte o funcionario que aparezca. Nunca se debe abandonar al paciente para ir a llamar.'),

  ('33333333-3333-3333-3333-333333333333',
   'CASO CLÍNICO: Una técnica paramédica del Servicio de Oncología accidentalmente derrama una bolsa de quimioterapia sobre su antebrazo y parte de la solución salpica al paciente en tratamiento. ¿Cuál es el orden correcto de las acciones inmediatas?',
   'Primero lavar su propio brazo, luego cortar la bomba de infusión del paciente',
   'Primero cortar la bomba de infusión del paciente, luego lavar su propio brazo con agua abundante por 10-15 minutos',
   'Llamar al médico tratante antes de realizar cualquier acción',
   'Activar el kit de derrame primero, luego atender al paciente y finalmente lavarse el brazo',
   'b', 'advanced',
   'Cuando el derrame involucra al paciente, la PRIMERA acción es cortar la bomba de infusión. Luego se realizan los primeros auxilios para la funcionaria (lavar con agua o suero 10-15 min). Posteriormente se informa al jefe directo y se notifica como accidente de trabajo.'),

  ('55555555-5555-5555-5555-555555555555',
   'CASO CLÍNICO: El equipo médico de UCI plantea limitar el esfuerzo terapéutico en un paciente con encefalopatía severa e irreversible, pero la familia se opone y exige mantener todas las medidas. El médico jefe tiene dudas éticas sobre cómo proceder. ¿Qué herramienta institucional corresponde activar?',
   'Presentar el caso al Comité Ético Científico (CEC) en Esmeralda 269',
   'Solicitar una reunión de arbitraje con la Dirección del Hospital',
   'Consultar al Comité de Ética Asistencial (CEA) enviando un correo a eticaclinica@ssdr.gob.cl con el resumen clínico',
   'Derivar el conflicto a la OIRS para mediación entre el equipo y la familia',
   'c', 'advanced',
   'Este caso involucra dificultad para conciliar derechos del paciente con la posición del equipo de salud, y dudas sobre adecuación del esfuerzo terapéutico: dos situaciones explícitas para consultar al CEA. Se accede enviando un correo a eticaclinica@ssdr.gob.cl con el resumen de Historia Clínica y el motivo de la solicitud.'),

  ('66666666-6666-6666-6666-666666666663',
   'CASO CLÍNICO: Durante un turno de noche, un técnico paramédico del Servicio de Cirugía sufre un pinchazo accidental con una aguja usada en un paciente con hepatitis B conocida. Hace la primera atención correcta (lavado 10-15 min). ¿Cuál es la ruta de atención correcta a seguir?',
   'Esperar al día siguiente hábil para ir al Policlínico del Personal y generar la DIAT',
   'Acudir al Policlínico del Personal de inmediato, ya que atiende las 24 horas',
   'Acudir a la UTI Médica (Anexo 652429) para atención y al día hábil siguiente ir al Policlínico del Personal para completar el proceso',
   'Informar solo al jefe de turno y esperar indicaciones sin acudir a ningún servicio esa noche',
   'c', 'advanced',
   'En horario inhábil (turno de noche), el funcionario debe acudir a la UTI Médica (Anexo 652429) para recibir atención médica inicial y profilaxis según el paciente fuente. Al día hábil siguiente, debe ir al Policlínico del Personal (Anexo 652207) para completar el proceso y generar la DIAT.'),

  ('66666666-6666-6666-6666-666666666665',
   'CASO CLÍNICO: Se activa el Código Verde en el Servicio de Medicina durante el horario de tarde. La enfermera supervisora está realizando un procedimiento de urgencia en un box. El técnico paramédico más antiguo del turno duda si puede asumir el rol de Líder. ¿Cuál es la respuesta correcta?',
   'No puede; debe esperar a que llegue un médico para asumir el liderazgo',
   'Sí puede; el Líder es el jefe, supervisor o quien esté a cargo del área en ese momento',
   'No puede; el liderazgo siempre recae en el profesional con más años de servicio en el hospital',
   'Debe llamar a la Dirección del Hospital para que designen a un Líder',
   'b', 'advanced',
   'El Líder de evacuación es quien esté a cargo del área en ese momento: el jefe de servicio, la supervisora o quien los reemplace. Si la supervisora está imposibilitada por un procedimiento de urgencia, quien deba quedar a cargo asume ese rol. El liderazgo no es exclusivo de médicos ni depende de antigüedad en el hospital.'),

  ('66666666-6666-6666-6666-666666666661',
   'CASO CLÍNICO: La hija de un paciente hospitalizado se acerca al Servicio de Medicina y pide al técnico paramédico de turno que le muestre la ficha clínica de su padre para saber cómo va su evolución. El técnico no la conoce personalmente. ¿Cuál es la respuesta institucional correcta?',
   'Mostrarle la Historia Clínica si ella acredita ser familiar directo con su cédula de identidad',
   'No mostrarle la Historia Clínica; orientarla a que el médico tratante le informe verbalmente sobre la evolución',
   'No mostrarle la Historia Clínica directamente; si requiere una copia, debe solicitarla a través de OIRS',
   'Mostrarle solo las evoluciones de enfermería, ya que las notas médicas son reservadas',
   'c', 'advanced',
   'La Historia Clínica es confidencial y contiene datos sensibles. Ningún funcionario puede entregarla o mostrarla directamente a familiares. Para obtener una copia, el paciente (o su representante legal) debe solicitarla formalmente a través de OIRS. La información verbal sobre evolución es función del médico tratante.'),

  ('55555555-5555-5555-5555-555555555555',
   'CASO CLÍNICO: Un investigador externo se presenta en el hospital con un protocolo de investigación clínica que involucra a pacientes de la UCI y solicita autorización para iniciar el estudio. ¿Qué instancia debe dar la aprobación obligatoria antes de que el estudio pueda comenzar?',
   'El Comité de Ética Asistencial (CEA), que sesiona los martes en el hospital',
   'La Dirección del Hospital Puerto Montt mediante resolución formal',
   'El Comité Ético Científico (CEC) del Servicio de Salud del Reloncaví',
   'Basta con la autorización del Jefe del Servicio de UCI donde se realizará el estudio',
   'c', 'advanced',
   'Toda investigación en seres humanos debe contar obligatoriamente con la aprobación del Comité Ético Científico (CEC). El CEC del Servicio de Salud del Reloncaví sesiona en Esmeralda 269, piso 2, oficina 202, Puerto Montt. El CEA tiene funciones distintas (dilemas éticos asistenciales) y no aprueba protocolos de investigación.')
on conflict do nothing;
